### ISSUE TITLE
How to use visual keywords?

### ISSUE THREAD

**Issue by wullxz** [alyvix/alyvix#1]
The documentation at http://www.alyvix.com/doc/test_case_building/visual_keywords.html does explain how to create visual keywords.  
But nowhere in that document does it explain how to use them.

In our case, when one of our created visual keywords is entered in a test case, the appliaction tells us that the keyword is not found.

How do we use visual keywords?

![alyvix_cannotfindkeyword](https://user-images.githubusercontent.com/813777/30481739-7feac450-9a20-11e7-818a-3b002fd9ad8e.png)

**Comment by franzmelchiori** [comment]
Hello wullxz, thanks for your feedback. That is written [here](http://alyvix.com/doc/test_case_building/test_case_editor.html#basic-operations), but maybe is not 100% clear. Imagine that you are building the test case `bla` and you have defined the `app_ready` visual keyword. To use it you have import the test case library `AlyvixProxybla` and insert the keyword `app_ready` at a certain point of your test. Please, ask for more details.

**Comment by wullxz** [comment]
Sorry for answering late. Your answer helped me; it's working now :)

**Comment by Ponchia** [comment]
Hello, I'm trying to import my visual keyboards, but I'm having trouble importing the library with the proxy. 

Is this procedure still working?

What I'have done is the following: 
- Created a project
- Created a visual keyboard (using the little alien icon)
- Created a test and tried to use my keywork (not working)
- Tried to import the proxy as described but failed.

**Comment by franzmelchiori** [comment]
Hello Ponchia, yes, it works more or less like you described. Create a project `blas`. Create a test `blat`. Create a keyword `blak`. Import `AlyvixProxyblas` and use the keyword `blak` in the test `blat`. I did it 1 godzillion times.
