### ISSUE TITLE
[bug][nagios mode] Performance data issue and how to contribute

### ISSUE THREAD

**Issue by tanguyvda** [alyvix/alyvix#6]
Hello everyone,

first of all thanks for this promising tool, I'm having a blast playing with it. 
You've made a lovely feature that allows us to handle thresholds for each step and run the robot with a nagios option. There's one mistake I've noticed (for the moment) regarding the performances data that you output. 

OK|my_step=1034ms;3s;5s;;

you shouldn't have the unit of measurement in the warn/crit part of the perfdata. And, you should use the same UOM for thresholds and metric value. Meaning that my example should return (for charts purposes)

OK|my_step=1034ms;3000;5000;;

I've made the change on my side but I've noticed that the default branch is the dev one. If I want to create a pull request, should I work on the dev branch or the master (or both ?)

here are the nagios guidelines for the perfomance data:
https://nagios-plugins.org/doc/guidelines.html#AEN200

regards

**Comment by franzmelchiori** [comment]
Dear tanguyvda,

Thanks for your encouragement! It motivates us.

You are right: it's a bug and you described the correct syntax.

Don't worry about the pull request: we're really closed to a new minor release, so we can easily include this fix. By the way, I'm sure you'll really enjoy Alyvix v3.1.0.

Can I ask you about your use cases? Do you use Alyvix for web applications, proprietary clients or streamed interfaces?

Thanks for your cooperation,
kind regards,
Francesco

**Comment by tanguyvda** [comment]
Hello,

here is the full use case:
context:
I'm working at Centreon (nagios fork at the beginning). We always used a tool to monitor user experience.  From now on, when people requested a tool to do that, we told them to use Selenium (2.x). That was easy to use and we made a connector. The usage was limited to websites and this is no longer the case because this version is not working on most modern website. 
To fix that, there is Selenium 3.x or Sikulix (in the list of the tools that we tested). Sadly those tools are not user friendly enough. We've heard about your software a few weeks ago and it looks like it's the perfect match for our users. 

use case:
most of our users need those kind of tools to make sure the services they provide are up and running fine and that the user experience is good. Most of the time, this is going to be related to web applications. In few cases, we can expect them to use Alyvix for a desktop client.  Since we are a fork of Nagios, we are compatible with their output format and we handle alerting, event logs and performance graph from this output. 
From what I've tested so far, on a personal note, I could see myself use Alyvix for QA purpose at Centreon (the section possibility being a nice feature for that I think)


on a technical standpoint (that could give you ideas), our standard way of using your kind of software is to use nsclient (with nsca) because we need a scheduler since by design you can only run one scenario at a time. We may think about creating some kind of python plugin so Alyvix send the results to our API and not just output it in the windows shell.

**Comment by franzmelchiori** [comment]
Hello tanguyvda,

Thanks a lot for sharing with us. We consider your story as a gift: we can learn from it, trying to keep Alyvix on track.

Alyvix is a FLOSS APM tool and it will remain as that: the idea is to provide a free/libre and open measurement system for the end-user experience through network applications.

You are a power user, you are able to integrate the Alyvix measures in your monitoring system and, probably, you would like to continue to do that.

Besides, we are developing Alyvix Server and we will release it soon on the market: it is a Windows service that is able to manage Windows multisessions, it schedules test cases on a set of given sessions, it collects all the measures and, finally, it exposes them through a web API to any monitoring system. There are a number of companies, sometimes not directly involved in the ICT sector, that consider really valuable this kind of service.

Thanks for cooperating,
best regards,
Francesco

**Comment by Sims24** [comment]
Hi @franzmelchiori 

I Can't wait to see this Alyvix Server on track. Exposing measurements & results through an API is a huge game-changer, that's simply great!

We are already pulling data from such endpoints with proprietary DEM/APM monitoring tool, and it will be great to do it with your solution too.

When you say you will release on the market, it means that the robot remains opensource but the Alyvix Server will be some kind of paid solutions/service? 

I'm managing integrations of third-party tools with Centreon with my team (@tanguyvda is part of it as you might guess). Feel free to reach me by mail if you want to go forward with such a partnership. (sbomm@centreon.com).

Thanks for your recent (fast) answers and the great tool! 
Simon

**Comment by franzmelchiori** [comment]
Hello @Sims24,

Thanks for your technical and enthusiastic feedbacks: they power our engines.

Yes, you're right: Alyvix Editor and Robot will remain a FLOSS tool (a free/libre and open source software), Alyvix Server will be a paid open source solution (a Windows Service powered by Python backend and session clients with a RedHat-like subscription model).

The idea is to provide a FLOSS measurement system for the end-user experience. One could have the time and will to integrate the output measures by their own. Others would like to rely on the solution that still is engineered by the Alyvix authors.

Georg Kostner, Alyvix business manager, will contact you soon to evaluate together a partnership.

Thanks again for your encouragements, but please do not hesitate to send us (here on GitHub is just fine) really candid feedbacks: precious matter for us.

Thanks for cooperating,
best regards,
Francesco
