### ISSUE TITLE
[feature request][nagios mode] add a perfdata that is the sum of all the other perfdata

### ISSUE THREAD

**Issue by tanguyvda** [alyvix/alyvix#8]
Hello again,

everything is pretty much in the title but here is an example

let say we have the following output:
`OK|open_twitter=0ms;;;; open_centreon_website=2341ms;;;; click_search_icon=2736ms;;;; `

it could be cool to have a new perfdata like that 
`OK|total=5077ms;;;; open_twitter=0ms;;;; open_centreon_website=2341ms;;;; click_search_icon=2736ms;;;; `

that's not that important, just giving you ideas  

Regards

**Comment by franzmelchiori** [comment]
Hello tanguyvda,

Actually, [we did it](https://www.alyvix.com/v2/learn/test_case_building/system_keywords.html#sum-perfdata) in Alyvix 2. It seemed a good idea, but in the end it drove to unclear outputs, especially when one of summed transactions was broken.

So, we left that feature designing Alyvix 3. The final test case chart results clearer (one color, one transaction) and more detailed: if you sum up a bunch of transactions and, for example, just one of them is really crucial (it has a significant variance) it could be better to leave it separate; viceversa, if the majority of the measures are crucial it is still be better to leave them separate.

On the other hand, if you really see that one transaction has always the same responsiveness in all the circumstances, so it is surely not critical, you could consider to not print it in the output, deselecting its `Measure` option.

Thanks for cooperating,
we really appreciate that,
best regards,
Francesco
